people_visualizer_node:
  ros__parameters:
    use_simulator: True

hunav_loader:
  ros__parameters:
    map: map_name
    publish_people: true
    agents:
      - agent1
      # - agent2
      # - agent3
      # - agent4
      # - agent5
    agent1: # agent walks back and forth
      id: 1
      skin: 2
      group_id: -1
      max_vel: 1.5
      radius: 0.3
      behavior:
        type: 1 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 2 # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 10.0  # seg
        once: true
        vel: 1.1
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 2.0
        social_force_factor: 2.0
        other_force_factor: 2.0
      init_pose:
        x: 3.0
        y: 3.0
        z: 1.250000
        h: 0.0
      goal_radius: 0.2
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
        - g3
      g0:
        x: 3.0
        y: -3.0
        h: 1.250000
      g1:
        x: -3.0
        y: -3.0
        h: 1.250000
      g2:
        x: -3.0
        y: 3.0
        h: 1.250000
      g3:
        x: 3.0
        y: 3.0
        h: 1.250000
    agent2: # agent walks back and forth
      id: 2
      skin: 2
      group_id: -1
      max_vel: 1.5
      radius: 0.3
      behavior: 
        type: 1 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 2 # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 10.0  # seg
        once: true
        vel: 1.1
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 2.0
        social_force_factor: 2.0
        other_force_factor: 2.0
      init_pose:
        x: 0.0
        y: 4.9
        z: 1.250000
        h: 0.0
      goal_radius: 0.2
      cyclic_goals: true
      goals:
        - near_lower_right
        - middle_intersection
        - left_wall1
        - upper_left
        - left_wall2
        - middle_intersection2
      middle_intersection:
        x: -2.1
        y: 5.0
        h: 1.250000
      middle_intersection2:
        x: -2.1
        y: 4.9
        h: 1.250000
      upper_left:
        x: -2.5
        y: 10.0
        h: 1.250000
      left_wall1:
        x: -3.2
        y: 7.29
        h: 1.250000
      left_wall2:
        x: -3.2
        y: 7.29
        h: 1.250000
      near_lower_right:
        x: 1.17
        y: 5.63
        h: 1.250000
    agent3: # agent walks back and forth
      id: 3
      skin: 1
      group_id: -1
      max_vel: 1.3
      radius: 0.3
      behavior: 
        type: 1 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 2 # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 10.0  # seg
        once: true
        vel: 1.5
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 2.0
        social_force_factor: 2.0
        other_force_factor: 2.0
      init_pose:
        x: -2.0
        y: 6.0
        z: 1.250000
        h: 0.0
      goal_radius: 0.2
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
        - g3
        - g4
      g0:
        x: -2.0
        y: 5.0
        h: 1.250000
      g1:
        x: 0.4
        y: 4.9
        h: 1.250000
      g2:
        x: -0.2
        y: 4.34
        h: 1.250000
      g3:
        x: -3.25
        y: 5.0
        h: 1.250000
      g4:
        x: -3.25
        y: 4.0
        h: 1.250000        
    agent4: # agent walks back and forth
      id: 4
      skin: 2
      group_id: -1
      max_vel: 1.5
      radius: 0.3
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 2 # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 10.0  # seg
        once: true
        vel: 1.6
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 2.0
        social_force_factor: 2.0
        other_force_factor: 2.0
      init_pose:
        x: -0.4888280928134918
        y: 9.381781578063965
        z: 1.250000
        h: 0.0
      goal_radius: 0.2
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
        - g3
        - g4
      g0:
        x: -2.0
        y: 5.0
        h: 1.250000
      g1:
        x: 0.4
        y: 4.9
        h: 1.250000
      g2:
        x: -3.25
        y: 5.0
        h: 1.250000
      g3:
        x: -3.25
        y: 4.0
        h: 1.250000
      g4:
        x: -0.2
        y: 4.34
        h: 1.250000
    agent5: # agent walks back and forth
      id: 5
      skin: 3
      group_id: -1
      max_vel: 1.5
      radius: 0.3
      behavior: 
        type: 1 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 2 # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 10.0  # seg
        once: true
        vel: 1.1
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 2.0
        social_force_factor: 2.0
        other_force_factor: 2.0
      init_pose:
        x: -2.5
        y: 8.0
        z: 1.250000
        h: 0.0
      goal_radius: 0.2
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
        - g3
      g0:
        x: -3.1
        y: 10.3
        h: 1.250000
      g1:
        x: -1.9
        y: 6.4
        h: 1.250000
      g2:
        x: -1.2
        y: 4.3
        h: 1.250000
      g3:
        x: -3.2
        y: 8.3
        h: 1.250000         

gazebo:
  ros__parameters:
    use_sim_time: True
    publish_rate: 60.0
